SED-2555: automation package services
exense/step pull request #164
Opened 2023-12-03 15:47 UTC by iegorov777

2023-12-04 09:41 UTC, david-stephan requested changes

2023-12-05 16:25 UTC, iegorov777 commented on step-automation-packages/step-automation-packages-manager/src/main/java/step/automation/packages/AutomationPackageManager.java
> +            oldPackage = getAutomationPackageById(explicitOldId, objectPredicate);
I've moved this check to `getAutomationPackageById()`, where I prepare different messages for 'not found' and 'not accessible'.

2023-12-05 16:32 UTC, iegorov777 commented on step-automation-packages/step-automation-packages-manager/src/main/java/step/automation/packages/AutomationPackageManager.java
> +            if (!Objects.equals(expectedName, actualName)) {
I've changed this. Now we can rename the package within the update, but we check that another package with this name (new name) already exists.

2023-12-07 08:57 UTC, david-stephan requested changes

2023-12-07 13:14 UTC, iegorov777 commented
Yes, indeed!
I've lost this line while moving code between local branches.
Fixed.

On Thu, Dec 7, 2023 at 11:57 AM David Stephan ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In
> step-automation-packages/step-automation-packages-manager/src/main/java/step/automation/packages/AutomationPackageManager.java
> <https://github.com/exense/step/pull/164#discussion_r1418615265>:
>
> > @@ -130,10 +170,28 @@ public PackageUpdateResult createOrUpdateAutomationPackage(boolean allowUpdate,
>              throw new AutomationPackageManagerException("Unable to read automation package", e);
>          }
>
> -        AutomationPackage oldPackage = getAutomationPackageByName(packageContent.getName(), objectPredicate);
> +        AutomationPackage oldPackage;
> +        if (explicitOldId != null) {
> +            oldPackage = getAutomationPackageById(explicitOldId, objectPredicate);
> +
> +            String newName = packageContent.getName();
> +            String oldName = oldPackage.getAttribute(AbstractOrganizableObject.NAME);
> +            if (!Objects.equals(newName, oldName)) {
> +                // the package with the same name shouldn't exist
> +                AutomationPackage existingPackageWithSameName = getAutomationPackageByName(newName, objectPredicate);
>
> @iegorov777 <https://github.com/iegorov777> shouldn't we check if
> existingPackageWithSameName isn't null here before throwing the exception?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/exense/step/pull/164#pullrequestreview-1769566753>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4L36E6NN45I5KDZO3HFAHLYIGAILAVCNFSM6AAAAABAE32XBWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTONRZGU3DMNZVGM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-12-07 13:15 UTC, iegorov777 commented on step-automation-packages/step-automation-packages-manager/src/main/java/step/automation/packages/AutomationPackageManager.java
> +                AutomationPackage existingPackageWithSameName = getAutomationPackageByName(newName, objectPredicate);
@david-stephan 
Yes, indeed!
I've lost this line while moving the code between local branches.
Fixed.

2023-12-07 13:18 UTC, merged