Sed 2725 fe   legend and filters   display entities names
exense/step pull request #195
Opened 2024-01-23 16:23 UTC by lucianbaciu

2024-01-23 20:48 UTC, lucianbaciu commented
@david-stephan some older parts of the file were tab indented. I slowly try to correct them

2024-01-24 08:22 UTC, david-stephan requested changes
@lucianbaciu comments will be added to internal tickets

2024-01-24 11:44 UTC, david-stephan submitted a review, later dismissed

2024-01-24 11:49 UTC, david-stephan approved these changes

2024-01-24 11:49 UTC, merged