Sed 2896 yaml source button does not work for plans with keyword versions
exense/step pull request #221
Opened 2024-02-27 19:10 UTC by iegorov777

2024-02-28 10:36 UTC, david-stephan requested changes
@iegorov777 in addition to individual comments, it would be nicer if we would support something like following syntax.
Keep the same for "simple" keyword
keyword: "Measurements"
For call keyword with multiple selection criteria
keyword: 
  name: "Measurements"
  version: "1.0.0"

2024-03-02 15:26 UTC, iegorov777 commented on step-plans/step-plans-yaml-parser/src/main/java/step/plans/parser/yaml/rules/KeywordSelectionRule.java
> +                }
@david-stephan 
Rewritten

2024-03-02 15:33 UTC, iegorov777 commented
@david-stephan 
In last commit I've changed the format in yaml.
Now the following syntax is supported.

```
- callKeyword:
   keyword: "myKeyword"
```

And also the extended one:

```
- callKeyword:
     keyword:
        name: "myKeyword5"
        version: "1.0.0"
```

2024-03-02 15:37 UTC, iegorov777 commented on step-controller/step-controller-server/src/main/java/step/core/plans/PlanServices.java
> +					throw ex;
@david-stephan 
Fixed

2024-03-06 08:10 UTC, david-stephan commented
PR on branch 24 was merged and cherry pick to master, closing this one without merge

2024-03-06 08:10 UTC, closed without merging