SED-2939 anonymous-user-wrongly-created-in-step-ee
exense/step pull request #228
Opened 2024-03-06 16:38 UTC by david-stephan

2024-03-07 17:02 UTC, cl-exense requested changes
Nice code! Just minor comments and quick things from my side.

2024-03-08 08:28 UTC, david-stephan commented on step-controller/step-controller-server/src/main/java/step/core/deployment/NoAuthenticationFilter.java
> +            anonymous.setRole("admin");
@cl-exense not sure what was exactly the question, the change to synchronized was necessary and a low level of concurrency is expected. Still the old code systematically accessing the DB was not required, I just refactored it.

2024-03-08 08:28 UTC, david-stephan commented
@cl-exense Thanks for the review, I think I addressed all points, let me know in there is anything else/new.

2024-03-08 08:55 UTC, cl-exense commented on step-controller/step-controller-server/src/main/java/step/core/deployment/NoAuthenticationFilter.java
> +            anonymous.setRole("admin");
The question was about the setRole(admin) specifically, but nice catch with the DB refactoring.

2024-03-08 08:56 UTC, cl-exense approved these changes

2024-03-08 09:11 UTC, merged