SED 2915-be-support-new-custom-columns
exense/step pull request #239
Opened 2024-04-09 15:00 UTC by david-stephan

2024-04-10 11:01 UTC, jeromecomte requested changes
The PR looks good. Haven't tried to understand the exact logic of SettingScopeRegistry. I would check the test coverage of this class to ensure that everything is properly covered by the unit tests

2024-04-10 11:41 UTC, david-stephan commented on step-controller/step-controller-server/src/main/java/step/migration/tasks/ScreenTemplateMigrationTask25.java
> +		screenInputs.remove(Filters.equals("screenId", "executionTable"));
Custom columns settings are currently not supported (i.e. either they are predefined by the FE or they are defined in the screen templates of Execution parameters, plans or functions). 
We could try to modify this migration tasks as part of the related ticket ([SED-3013]). Note that implementing such a migration will require to create the default settings (predefined columns) in the BE

2024-04-10 11:46 UTC, jeromecomte commented on step-controller/step-controller-server/src/main/java/step/migration/tasks/ScreenTemplateMigrationTask25.java
> +		screenInputs.remove(Filters.equals("screenId", "executionTable"));
I thought we could do the following as part of this migration task: For all standard colums (columns that are now predefined in the FE) that are not displayed per default, could we simply display them if a screenInputs corresponding to the column?

For non standard columns I wouldn't do anything but just log a warning in the migration logs

2024-04-11 07:59 UTC, jeromecomte submitted a review, later dismissed

2024-04-11 07:59 UTC, jeromecomte commented on step-controller/step-controller-server/src/main/java/step/core/plans/PlanPlugin.java
>  		ScreenInputAccessor screenInputAccessor = context.get(ScreenInputAccessor.class);
@david-stephan doesn't seem to be used anymore

2024-05-02 12:18 UTC, merged