SED-3580-expose getLastExecutionByTaskId
exense/step pull request #357
Opened 2024-11-21 09:06 UTC by lucianbaciu

2024-11-21 15:13 UTC, david-stephan requested changes
Small change requested

2024-11-21 15:13 UTC, david-stephan commented on step-controller/step-controller-server/src/main/java/step/core/execution/ExecutionServices.java
> +	@POST
@lucianbaciu I think  a GET method would be more appropriate in this case.

2024-11-25 07:48 UTC, david-stephan approved these changes

2024-12-03 10:04 UTC, lucianbaciu commented
@david-stephan please check out my last changes

2024-12-03 12:19 UTC, david-stephan requested changes
See individual comments

2024-12-03 17:52 UTC, lucianbaciu commented on step-controller-plugins/step-controller-plugins-timeseries/src/main/java/step/plugins/timeseries/TimeSeriesService.java
> +        // TODO permissions? we don't have projectId yet
@david-stephan I'm sorry, this was an old comment before our conversations

2024-12-04 13:56 UTC, david-stephan submitted a review, later dismissed

2024-12-13 08:03 UTC, david-stephan approved these changes

2024-12-18 10:20 UTC, merged