Sed 3347 implement new yaml plan editor or allow to load a yaml plan in the UI plan editor
exense/step pull request #366
Opened 2024-12-16 16:49 UTC by iegorov777

2024-12-17 15:33 UTC, david-stephan commented on step-plans/step-plans-yaml-parser/src/main/java/step/plans/parser/yaml/editor/LineNumberByJsonPointerResolver.java
> +        // TODO: maybe optimize and avoid creation of new ObjectMapper and factory for each source
@iegorov777 yes, I don't think the creation of com.jayway.jsonpath.Configuration has to be done for each invocation of findLineNumbers. If it's thread safe a single instance should be enough

2024-12-17 15:33 UTC, david-stephan commented on step-plans/step-plans-yaml-parser/src/main/java/step/plans/parser/yaml/editor/YamlEditorPlanTypeCompiler.java
> +                            new LineNumberByJsonPointerResolver().findLineNumbers(
Do we need a new instance of LineNumberByJsonPointerResolver each time?

2025-01-10 10:43 UTC, david-stephan requested changes

2025-01-10 10:43 UTC, david-stephan commented on step-controller/step-controller-server/src/main/java/step/core/plans/PlanServices.java
> +			throw new ControllerServiceException(400, "Plan type is not resolved by name " + planTypeName);
@iegorov777 since this is a controller exception (visible by the user) I would rephrase it to something like "Plan type {} is not supported."

2025-01-10 10:43 UTC, david-stephan commented on step-controller/step-controller-server/src/main/java/step/core/plans/PlanServices.java
> +			throw new ControllerServiceException(400, "Plan is undefined");
I would write something more precise, user friendly "The submitted plan to be saved is empty or null"

2025-01-10 10:43 UTC, david-stephan commented on step-plans/step-plans-yaml-parser/src/main/java/step/plans/parser/yaml/editor/YamlEditorPlanType.java
> +        YamlEditorPlan plainTextPlan = new YamlEditorPlan();
variable should be renamed to yamlPlan or yamlEditorPlan

2025-01-10 10:43 UTC, david-stephan commented on step-plans/step-plans-yaml-parser/src/main/java/step/plans/parser/yaml/editor/YamlEditorPlanTypeCompiler.java
> +        if (root != null && root.getClass() == parsedRoot.getClass()) {
@iegorov777  Can you explain why this is required? Also why is it not required if the class of the root change?

2025-01-26 18:11 UTC, iegorov777 commented on step-plans/step-plans-yaml-parser/src/main/java/step/plans/parser/yaml/editor/LineNumberByJsonPointerResolver.java
> +        // TODO: maybe optimize and avoid creation of new ObjectMapper and factory for each source
@david-stephan 
Already fixed now

2025-01-26 18:12 UTC, iegorov777 commented on step-plans/step-plans-yaml-parser/src/main/java/step/plans/parser/yaml/editor/YamlEditorPlanTypeCompiler.java
> +                            new LineNumberByJsonPointerResolver().findLineNumbers(
@david-stephan , already created once in constructor

2025-01-26 18:16 UTC, iegorov777 commented on step-plans/step-plans-yaml-parser/src/main/java/step/plans/parser/yaml/editor/YamlEditorPlanTypeCompiler.java
> +        if (root != null && root.getClass() == parsedRoot.getClass()) {
@david-stephan 
I fact I don't know. This is copied from `PlainTextPlanCompiler` in Step Enterprise.

2025-02-24 08:57 UTC, david-stephan submitted a review, later dismissed

2025-03-05 12:19 UTC, merged